### ISSUE TITLE
feat: Hivemind improvements

### ISSUE THREAD

**Issue by amindadgar** [TogetherCrew/hivemind-bot#109]
We need to improve our hivemind-bot and follow the below tasks 

**Tasks**
- [x]  Skip answering questions with non-relevant context information
- [ ]  Skip answering nonsense questions ("1111", "hello")
- [x]  Skip included less similar context information in prompt (excluding lower similarity scores)
